/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "raccoochat_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace raccoochat {


User::~User() throw() {
}


void User::__set_userIndex(const int32_t val) {
  this->userIndex = val;
}

void User::__set_userPassword(const std::string& val) {
  this->userPassword = val;
}

uint32_t User::read(::apache::thrift::protocol::TProtocol* iprot) {

  apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->userIndex);
          this->__isset.userIndex = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->userPassword);
          this->__isset.userPassword = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t User::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("User");

  xfer += oprot->writeFieldBegin("userIndex", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->userIndex);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("userPassword", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->userPassword);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(User &a, User &b) {
  using ::std::swap;
  swap(a.userIndex, b.userIndex);
  swap(a.userPassword, b.userPassword);
  swap(a.__isset, b.__isset);
}

User::User(const User& other0) {
  userIndex = other0.userIndex;
  userPassword = other0.userPassword;
  __isset = other0.__isset;
}
User& User::operator=(const User& other1) {
  userIndex = other1.userIndex;
  userPassword = other1.userPassword;
  __isset = other1.__isset;
  return *this;
}
void User::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "User(";
  out << "userIndex=" << to_string(userIndex);
  out << ", " << "userPassword=" << to_string(userPassword);
  out << ")";
}


UserData::~UserData() throw() {
}


void UserData::__set_userName(const std::string& val) {
  this->userName = val;
}

void UserData::__set_registrationDate(const std::string& val) {
  this->registrationDate = val;
}

void UserData::__set_allMessagesIndex(const int32_t val) {
  this->allMessagesIndex = val;
}

void UserData::__set_privateMessagesIndex(const int32_t val) {
  this->privateMessagesIndex = val;
}

uint32_t UserData::read(::apache::thrift::protocol::TProtocol* iprot) {

  apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->userName);
          this->__isset.userName = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->registrationDate);
          this->__isset.registrationDate = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->allMessagesIndex);
          this->__isset.allMessagesIndex = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->privateMessagesIndex);
          this->__isset.privateMessagesIndex = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t UserData::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("UserData");

  xfer += oprot->writeFieldBegin("userName", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->userName);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("registrationDate", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->registrationDate);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("allMessagesIndex", ::apache::thrift::protocol::T_I32, 3);
  xfer += oprot->writeI32(this->allMessagesIndex);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("privateMessagesIndex", ::apache::thrift::protocol::T_I32, 4);
  xfer += oprot->writeI32(this->privateMessagesIndex);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(UserData &a, UserData &b) {
  using ::std::swap;
  swap(a.userName, b.userName);
  swap(a.registrationDate, b.registrationDate);
  swap(a.allMessagesIndex, b.allMessagesIndex);
  swap(a.privateMessagesIndex, b.privateMessagesIndex);
  swap(a.__isset, b.__isset);
}

UserData::UserData(const UserData& other2) {
  userName = other2.userName;
  registrationDate = other2.registrationDate;
  allMessagesIndex = other2.allMessagesIndex;
  privateMessagesIndex = other2.privateMessagesIndex;
  __isset = other2.__isset;
}
UserData& UserData::operator=(const UserData& other3) {
  userName = other3.userName;
  registrationDate = other3.registrationDate;
  allMessagesIndex = other3.allMessagesIndex;
  privateMessagesIndex = other3.privateMessagesIndex;
  __isset = other3.__isset;
  return *this;
}
void UserData::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "UserData(";
  out << "userName=" << to_string(userName);
  out << ", " << "registrationDate=" << to_string(registrationDate);
  out << ", " << "allMessagesIndex=" << to_string(allMessagesIndex);
  out << ", " << "privateMessagesIndex=" << to_string(privateMessagesIndex);
  out << ")";
}


SimpleMessage::~SimpleMessage() throw() {
}


void SimpleMessage::__set_time(const std::string& val) {
  this->time = val;
}

void SimpleMessage::__set_userName(const std::string& val) {
  this->userName = val;
}

void SimpleMessage::__set_textMessage(const std::string& val) {
  this->textMessage = val;
}

uint32_t SimpleMessage::read(::apache::thrift::protocol::TProtocol* iprot) {

  apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->time);
          this->__isset.time = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->userName);
          this->__isset.userName = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->textMessage);
          this->__isset.textMessage = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t SimpleMessage::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("SimpleMessage");

  xfer += oprot->writeFieldBegin("time", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->time);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("userName", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->userName);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("textMessage", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString(this->textMessage);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(SimpleMessage &a, SimpleMessage &b) {
  using ::std::swap;
  swap(a.time, b.time);
  swap(a.userName, b.userName);
  swap(a.textMessage, b.textMessage);
  swap(a.__isset, b.__isset);
}

SimpleMessage::SimpleMessage(const SimpleMessage& other4) {
  time = other4.time;
  userName = other4.userName;
  textMessage = other4.textMessage;
  __isset = other4.__isset;
}
SimpleMessage& SimpleMessage::operator=(const SimpleMessage& other5) {
  time = other5.time;
  userName = other5.userName;
  textMessage = other5.textMessage;
  __isset = other5.__isset;
  return *this;
}
void SimpleMessage::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "SimpleMessage(";
  out << "time=" << to_string(time);
  out << ", " << "userName=" << to_string(userName);
  out << ", " << "textMessage=" << to_string(textMessage);
  out << ")";
}


InvalidNameException::~InvalidNameException() throw() {
}


void InvalidNameException::__set_errorCode(const int32_t val) {
  this->errorCode = val;
}

void InvalidNameException::__set_errorMessage(const std::string& val) {
  this->errorMessage = val;
}

uint32_t InvalidNameException::read(::apache::thrift::protocol::TProtocol* iprot) {

  apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->errorCode);
          this->__isset.errorCode = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->errorMessage);
          this->__isset.errorMessage = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t InvalidNameException::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("InvalidNameException");

  xfer += oprot->writeFieldBegin("errorCode", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->errorCode);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("errorMessage", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->errorMessage);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(InvalidNameException &a, InvalidNameException &b) {
  using ::std::swap;
  swap(a.errorCode, b.errorCode);
  swap(a.errorMessage, b.errorMessage);
  swap(a.__isset, b.__isset);
}

InvalidNameException::InvalidNameException(const InvalidNameException& other6) : TException() {
  errorCode = other6.errorCode;
  errorMessage = other6.errorMessage;
  __isset = other6.__isset;
}
InvalidNameException& InvalidNameException::operator=(const InvalidNameException& other7) {
  errorCode = other7.errorCode;
  errorMessage = other7.errorMessage;
  __isset = other7.__isset;
  return *this;
}
void InvalidNameException::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "InvalidNameException(";
  out << "errorCode=" << to_string(errorCode);
  out << ", " << "errorMessage=" << to_string(errorMessage);
  out << ")";
}

const char* InvalidNameException::what() const throw() {
  try {
    std::stringstream ss;
    ss << "TException - service has thrown: " << *this;
    this->thriftTExceptionMessageHolder_ = ss.str();
    return this->thriftTExceptionMessageHolder_.c_str();
  } catch (const std::exception&) {
    return "TException - service has thrown: InvalidNameException";
  }
}

} // namespace
