/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "raccoochat_constants.h"

namespace raccoochat {

const raccoochatConstants g_raccoochat_constants;

raccoochatConstants::raccoochatConstants() {
  MAP_COMMANDS.insert(std::make_pair("/users", "returns all users that are online."));
  MAP_COMMANDS.insert(std::make_pair("/last", "returns last five messages"));
  MAP_COMMANDS.insert(std::make_pair("/exit", "sing out from the chat"));
  MAP_COMMANDS.insert(std::make_pair(".{username}", "send a private message for {username}"));

}

} // namespace

