/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef raccoochat_CONSTANTS_H
#define raccoochat_CONSTANTS_H

#include "raccoochat_types.h"

namespace raccoochat {

class raccoochatConstants {
 public:
  raccoochatConstants();

  std::map<std::string, std::string>  MAP_COMMAND;
};

extern const raccoochatConstants g_raccoochat_constants;

} // namespace

#endif
